/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bookriddle.view;

import br.com.bookriddle.utilities.ImageTransfer;
import br.com.bookriddle.controller.LivroDao;
import br.com.bookriddle.interfaces.ScreenConfig;
import br.com.bookriddle.interfaces.Verificacao;
import br.com.bookriddle.model.Livro;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Marcos Vinícius Brás de Oliveira
 */
public class FrmCadastroLivro extends javax.swing.JFrame implements Verificacao, ScreenConfig {

    /**
     * Creates new form FrmPrincipal
     */
    private ImageIcon imagem = null; //ImageIcon que vai guardar a imagem selecionada
    private File imagem_selecionada = null;
    private String caminho = null;
    private final int ACTION_SELECT = 1;
    private final int ACTION_REMOVE = 2;
    private String SELECIONAR = "Selecionar Imagem", REMOVER = "Remover Imagem";
    private int state = ACTION_SELECT;
    private ImageTransfer it;
    private String destination_path = null;
    private FrmListaLivro busca;

    public FrmCadastroLivro() {
        initComponents();
        frameConfig();
    }

    public FrmCadastroLivro(FrmListaLivro busca) {
        initComponents();
        frameConfig();
        this.busca = busca;
    }

    @Override
    public void frameConfig() {
        this.setLocationRelativeTo(null);

        try {
            this.setIconImage(ImageIO.read(new File("src/br/com/bookriddle/imagens/liphia_icon.png")));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public boolean validarCampos() {
        boolean resultado = false;

        try {
            int paginas = Integer.parseInt(txt_paginas.getText());
            int quantidade = Integer.parseInt(txt_quantidade.getText());
            int ano = Integer.parseInt(txt_ano.getText());
            int prateleira = Integer.parseInt(txt_prateleira.getText());
            resultado = true;
        } catch (Exception e) {
            resultado = false;
        }

        if (!txt_isbn.getText().equals("") && !txt_titulo.getText().equals("") && !txt_autor.getText().equals("")
                && !txt_area.getText().equals("") && !txt_edicao.getText().equals("") && !txt_editora.getText().equals("")
                && !txt_paginas.getText().equals("") && !txt_quantidade.equals("") && !txt_ano.getText().equals("") && resultado) {

            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_autor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_edicao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_ano = new javax.swing.JTextField();
        txt_quantidade = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_area = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_editora = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_paginas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_isbn = new javax.swing.JTextField();
        txt_prateleira = new javax.swing.JTextField();
        txt_armario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_img = new javax.swing.JLabel();
        btn_selecionar = new javax.swing.JPanel();
        lbl_btn_img = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JPanel();
        label_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Riddle - Cadastro de Livros");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(237, 250, 251));

        panel1.setMaximumSize(new java.awt.Dimension(486, 407));
        panel1.setMinimumSize(new java.awt.Dimension(486, 407));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Título");

        txt_titulo.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Autor");

        txt_autor.setForeground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Edição");

        txt_edicao.setForeground(new java.awt.Color(51, 51, 51));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Quantidade");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Armário");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Prateleira");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Ano");

        txt_ano.setForeground(new java.awt.Color(51, 51, 51));

        txt_quantidade.setForeground(new java.awt.Color(51, 51, 51));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Área");

        txt_area.setForeground(new java.awt.Color(51, 51, 51));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Editora");

        txt_editora.setForeground(new java.awt.Color(51, 51, 51));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Páginas");

        txt_paginas.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("ISBN");

        txt_isbn.setForeground(new java.awt.Color(51, 51, 51));

        txt_prateleira.setForeground(new java.awt.Color(51, 51, 51));

        txt_armario.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel11)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_edicao)
                            .addComponent(txt_editora)
                            .addComponent(txt_paginas, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_armario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_prateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_isbn)
                            .addComponent(txt_autor)
                            .addComponent(txt_titulo)
                            .addComponent(txt_area, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txt_edicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txt_editora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txt_paginas)
                        .addGap(1, 1, 1)))
                .addGap(8, 8, 8)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_prateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_armario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        jPanel2.setMaximumSize(new java.awt.Dimension(486, 407));
        jPanel2.setMinimumSize(new java.awt.Dimension(486, 407));
        jPanel2.setPreferredSize(new java.awt.Dimension(486, 407));

        jScrollPane1.setBorder(null);

        lbl_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(lbl_img);

        btn_selecionar.setBackground(new java.awt.Color(227, 6, 19));
        btn_selecionar.setMaximumSize(new java.awt.Dimension(230, 40));
        btn_selecionar.setMinimumSize(new java.awt.Dimension(230, 40));
        btn_selecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_selecionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_selecionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_selecionarMouseExited(evt);
            }
        });

        lbl_btn_img.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_btn_img.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_img.setText("Selecionar Imagem");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bookriddle/imagens/white_cam_small.png"))); // NOI18N

        javax.swing.GroupLayout btn_selecionarLayout = new javax.swing.GroupLayout(btn_selecionar);
        btn_selecionar.setLayout(btn_selecionarLayout);
        btn_selecionarLayout.setHorizontalGroup(
            btn_selecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_selecionarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lbl_btn_img)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btn_selecionarLayout.setVerticalGroup(
            btn_selecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btn_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_cadastrar.setBackground(new java.awt.Color(227, 6, 19));
        btn_cadastrar.setPreferredSize(new java.awt.Dimension(208, 52));
        btn_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cadastrarMouseExited(evt);
            }
        });

        label_btn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label_btn.setForeground(new java.awt.Color(255, 255, 255));
        label_btn.setText("Cadastrar");

        javax.swing.GroupLayout btn_cadastrarLayout = new javax.swing.GroupLayout(btn_cadastrar);
        btn_cadastrar.setLayout(btn_cadastrarLayout);
        btn_cadastrarLayout.setHorizontalGroup(
            btn_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cadastrarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(label_btn)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        btn_cadastrarLayout.setVerticalGroup(
            btn_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastrarMouseClicked
        if (validarCampos()) {
            Livro l = new Livro();
            l.setIsbn(txt_isbn.getText());
            l.setTitulo(txt_titulo.getText());
            l.setAutor(txt_autor.getText());
            l.setArea(txt_area.getText());
            l.setEdicao(txt_edicao.getText());
            l.setEditora(txt_editora.getText());
            l.setPaginas(Integer.parseInt(txt_paginas.getText()));
            l.setQuantidade(Integer.parseInt(txt_quantidade.getText()));
            l.setAno(Integer.parseInt(txt_ano.getText()));
            l.setStatus(Livro.STATUS_ATIVO);

            if (txt_armario.getText().equals("")) {
                l.setArmario(null);
                l.setPrateleira(null);
            } else {
                l.setArmario(txt_armario.getText());
                l.setPrateleira(txt_prateleira.getText());
            }

            l.setUrl(destination_path);

            LivroDao dao = new LivroDao(l);
            boolean resultado = dao.inserir();
            if(resultado) {
                JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso.");
            }
            it.transferirImagem();
            imagem_selecionada = null;
            busca.setList(dao.buscarTodos("where status_livro != 0 order by titulo"));
            dao.closeConnection();
        } else {
            JOptionPane.showMessageDialog(null, "Verifique se todos os campos foram preenchidos corretamente");
        }
    }//GEN-LAST:event_btn_cadastrarMouseClicked

    private void btn_cadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastrarMouseEntered
        btn_cadastrar.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_btn_cadastrarMouseEntered

    private void btn_cadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastrarMouseExited
        btn_cadastrar.setBackground(new Color(227, 6, 19));
    }//GEN-LAST:event_btn_cadastrarMouseExited

    private void btn_selecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selecionarMouseClicked
        if (state == ACTION_SELECT) { // Condição caso o botão estiver como "Selecionar Imagem" na hora do clique
            try {
                JFileChooser chooser = new JFileChooser(); // Criando um seletor de imagem
                FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG Images", "jpg", "jpeg", "png");  //Cria um filtro
                chooser.setFileFilter(filter);  //Altera o filtro do JFileChooser
                int ok = chooser.showOpenDialog(btn_selecionar);

                if (ok == JFileChooser.APPROVE_OPTION) { // Caso retorne com alguma imagem, ela deverá ser mostrada no Frame
                    lbl_btn_img.setText(REMOVER);
                    state = ACTION_REMOVE; // o botão "Selecionar Imagem" vira "Remover Imagem"
                    imagem_selecionada = chooser.getSelectedFile(); //Pegando a imagem selecionada
                    imagem = new ImageIcon(imagem_selecionada.getAbsolutePath()); // Pegando o caminho da imagem selecionada
                    ImageIcon thumbnail = new ImageIcon(imagem.getImage().getScaledInstance(-12, lbl_img.getHeight(), Image.SCALE_SMOOTH));
                    lbl_img.setIcon(thumbnail);

                    it = new ImageTransfer(imagem_selecionada, imagem_selecionada.getAbsolutePath());
                    destination_path = (it.getDestinationPath()); // Gerando o diretório destino
                } else {
                    chooser.cancelSelection();
                    destination_path = null;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao selecionar a imagem, tente novamente");
                e.printStackTrace();
                destination_path = null;
            }
        } else { // Condição caso o botão estiver como "Remover Imagem" na hora do clique
            lbl_btn_img.setText(SELECIONAR);
            lbl_img.setIcon(null);
            state = ACTION_SELECT; // Botão se "Remover Imagem" se torna "Selecionar Imagem"
            imagem_selecionada = null;
            destination_path = null;
        }
    }//GEN-LAST:event_btn_selecionarMouseClicked

    private void btn_selecionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selecionarMouseEntered
        btn_selecionar.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_btn_selecionarMouseEntered

    private void btn_selecionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selecionarMouseExited
        btn_selecionar.setBackground(new Color(227, 6, 19));
    }//GEN-LAST:event_btn_selecionarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_cadastrar;
    private javax.swing.JPanel btn_selecionar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_btn;
    private javax.swing.JLabel lbl_btn_img;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JTextField txt_area;
    private javax.swing.JTextField txt_armario;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_edicao;
    private javax.swing.JTextField txt_editora;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_paginas;
    private javax.swing.JTextField txt_prateleira;
    private javax.swing.JTextField txt_quantidade;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
