/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bookriddle.view;

import br.com.bookriddle.controller.FuncionarioDao;
import br.com.bookriddle.interfaces.ScreenConfig;
import br.com.bookriddle.interfaces.ListagemModel;
import br.com.bookriddle.model.Funcionario;
import br.com.bookriddle.model.Supervisor;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Vinícius Brás de Oliveira
 */
public class FrmSelecionarFuncionario extends javax.swing.JFrame implements ScreenConfig, ListagemModel {

    /**
     * Creates new form FrmPrincipal
     */
    
    private DefaultTableModel modelo;
    private Funcionario funcionario;
    private ArrayList<Funcionario> listFun;
    private String[] campo = {"todas", "nome", "matricula", "email"};
    private Supervisor sup;
    private FrmEmprestimoDireto emprestimo;
    private FrmUsuario usuario;
    
    public FrmSelecionarFuncionario() {
        initComponents();
    }
    
    // Construtor chamado pela tela de empréstimo direto
    public FrmSelecionarFuncionario(FrmEmprestimoDireto emprestimo) {
        initComponents();
        frameConfig();
        this.emprestimo = emprestimo;
        modelo = new DefaultTableModel();
        tabela_funcionario.setModel(modelo);
        
        modelo.addColumn("Matrícula");
        modelo.addColumn("Nome");
        modelo.addColumn("Email");
        modelo.addColumn("Telefone");
        
        FuncionarioDao dao = new FuncionarioDao();
        listFun = (ArrayList<Funcionario>)dao.buscarTodos("where status_funcionario != 0 order by nome");
        dao.closeConnection();
        atualizarTabela();
    }
    
    // Construtor chamado pela tela FrmUsuario
    public FrmSelecionarFuncionario(FrmUsuario usuario) {
        initComponents();
        frameConfig();
        this.usuario = usuario;
        modelo = new DefaultTableModel();
        tabela_funcionario.setModel(modelo);
        
        modelo.addColumn("Matrícula");
        modelo.addColumn("Nome");
        modelo.addColumn("Email");
        modelo.addColumn("Telefone");
        
        FuncionarioDao dao = new FuncionarioDao();
        listFun = (ArrayList<Funcionario>)dao.buscarTodos("where status_funcionario != 0 order by nome");
        dao.closeConnection();
        atualizarTabela();
    }
    
    @Override
    public void atualizarTabela() {
        modelo.setRowCount(0);
        if(listFun != null) {
            for(Funcionario f : listFun) {
                modelo.addRow(new String[]{f.getMatricula(), f.getNome(), f.getEmail(), f.getTelefone()});
            }
        }
    }
    
    @Override
    public boolean isSelected() {
        int count = tabela_funcionario.getSelectedRowCount();
        
        if(count > 0) {
            if(count == 1) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Selecione apenas um funcionário");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma funcionário");
            return false;
        }
    }
    
    @Override
    public void setList(ArrayList<?> list) {
        this.listFun = (ArrayList<Funcionario>)list;
        atualizarTabela();
    }
    
    @Override
    public void frameConfig() {
        this.setLocationRelativeTo(null);
        
        try {
            this.setIconImage(ImageIO.read(new File("src/br/com/bookriddle/imagens/liphia_icon.png")));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    @Override
    public void verDetalhes() {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_funcionario = new javax.swing.JTable();
        btn_selecionar = new javax.swing.JPanel();
        label_btn2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_condicao = new javax.swing.JComboBox();
        txt_busca = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Riddle - Seleção de Funcionário");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(237, 250, 251));

        tabela_funcionario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tabela_funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela_funcionario);

        btn_selecionar.setBackground(new java.awt.Color(227, 6, 19));
        btn_selecionar.setMaximumSize(new java.awt.Dimension(268, 50));
        btn_selecionar.setMinimumSize(new java.awt.Dimension(268, 50));
        btn_selecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_selecionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_selecionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_selecionarMouseExited(evt);
            }
        });

        label_btn2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label_btn2.setForeground(new java.awt.Color(255, 255, 255));
        label_btn2.setText("Selecionar");

        javax.swing.GroupLayout btn_selecionarLayout = new javax.swing.GroupLayout(btn_selecionar);
        btn_selecionar.setLayout(btn_selecionarLayout);
        btn_selecionarLayout.setHorizontalGroup(
            btn_selecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_selecionarLayout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(label_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        btn_selecionarLayout.setVerticalGroup(
            btn_selecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(227, 6, 19));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bookriddle/imagens/white_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Pesquisar por");

        cb_condicao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_condicao.setForeground(new java.awt.Color(51, 51, 51));
        cb_condicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Matrícula", "Nome", "Email" }));

        txt_busca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_busca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_busca.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txt_buscaTextValueChanged(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Selecione um funcionário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_condicao, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
            .addComponent(btn_selecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_condicao, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btn_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscaTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txt_buscaTextValueChanged
        String busca = txt_busca.getText();
        if(!busca.equals("")) {
            int idx = cb_condicao.getSelectedIndex();
            String clause = null;
            
            if(idx == 0) {
                clause = "where (" + campo[1] + " like '%" + busca + "%' or " + campo[2] + " like '%" + busca + "%' or "
                        + campo[3] + " like '%" + busca + "%') and (status_funcionario != 0) order by nome";
            } else {
                clause = "where " + campo[idx] + " like '%" + busca + "%' and status_funcionario != 0 order by nome";
            }
   
            FuncionarioDao dao = new FuncionarioDao();
            listFun = (ArrayList<Funcionario>)dao.buscarTodos(clause);
            dao.closeConnection();
            atualizarTabela();
        }
    }//GEN-LAST:event_txt_buscaTextValueChanged

    private void btn_selecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selecionarMouseClicked
        if(isSelected()) {
            if(emprestimo != null) {
                funcionario = listFun.get(tabela_funcionario.getSelectedRow());
                emprestimo.setFuncionario(funcionario);
                dispose();
            }
            
            if(usuario != null) {
                funcionario = listFun.get(tabela_funcionario.getSelectedRow());
                usuario.setFuncionario(funcionario);
                dispose();
            }
        }
    }//GEN-LAST:event_btn_selecionarMouseClicked

    private void btn_selecionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selecionarMouseEntered
        btn_selecionar.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_btn_selecionarMouseEntered

    private void btn_selecionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selecionarMouseExited
        btn_selecionar.setBackground(new Color(227,6,19));
    }//GEN-LAST:event_btn_selecionarMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSelecionarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_selecionar;
    private javax.swing.JComboBox cb_condicao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_btn2;
    private javax.swing.JTable tabela_funcionario;
    private java.awt.TextField txt_busca;
    // End of variables declaration//GEN-END:variables
}
