/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bookriddle.view;

import br.com.bookriddle.controller.EditoraDao;
import br.com.bookriddle.interfaces.ListagemModel;
import br.com.bookriddle.model.Editora;
import br.com.bookriddle.model.Supervisor;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Vinícius Brás de Oliveira
 */
public class FrmSelecionarEditora extends javax.swing.JFrame implements ListagemModel {

    /**
     * Creates new form FrmSelecionarAutor
     */
    private DefaultTableModel modelo;
    private Editora editora;
    private ArrayList<Editora> listEditora;
    private Supervisor sup;
    private FrmCadastroLivroTeste cadlivro;
    private FrmEditarLivro editarLivro;
    private FrmVerLivro verLivro;

    public FrmSelecionarEditora() {
        initComponents();
    }

    // Construtor chamado pela tela "Controle de Livros"
    public FrmSelecionarEditora(FrmCadastroLivroTeste cadlivro) {
        initComponents();
        setLocationRelativeTo(null);
        this.cadlivro = cadlivro;
        modelo = new DefaultTableModel();
        tabela_editora.setModel(modelo);

        modelo.addColumn("Editora");

        EditoraDao aDao = new EditoraDao();
        listEditora = (ArrayList<Editora>) aDao.buscarTodos("where status_editora != 0 order by nome");
        aDao.closeConnection();
        atualizarTabela();
    }
    
    public FrmSelecionarEditora(FrmVerLivro verLivro) {
        initComponents();
        setLocationRelativeTo(null);
        this.verLivro = verLivro;
        modelo = new DefaultTableModel();
        tabela_editora.setModel(modelo);

        modelo.addColumn("Editora");

        EditoraDao aDao = new EditoraDao();
        listEditora = (ArrayList<Editora>) aDao.buscarTodos("where status_editora != 0 order by nome");
        aDao.closeConnection();
        atualizarTabela();
    }
    
    public FrmSelecionarEditora(FrmEditarLivro editarLivro) {
        initComponents();
        setLocationRelativeTo(null);
        this.editarLivro = editarLivro;
        modelo = new DefaultTableModel();
        tabela_editora.setModel(modelo);

        modelo.addColumn("Editora");

        EditoraDao aDao = new EditoraDao();
        listEditora = (ArrayList<Editora>) aDao.buscarTodos("where status_editora != 0 order by nome");
        aDao.closeConnection();
        atualizarTabela();
    }

    @Override
    public void atualizarTabela() {
        modelo.setRowCount(0);
        if (listEditora != null) {
            for (Editora e : listEditora) {
                modelo.addRow(new String[]{e.getNome()});
            }
        }
    }

    @Override
    public boolean isSelected() {
        int count = tabela_editora.getSelectedRowCount();

        if (count > 0) {
            if (count == 1) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Selecione apenas uma editora");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma editora");
            return false;
        }
    }

    @Override
    public void setList(ArrayList<?> list) {
        
    }

    @Override
    public void verDetalhes() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_editora = new javax.swing.JTable();
        btn_selecionar = new javax.swing.JPanel();
        label_btn2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_busca = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        btn_adicionar = new javax.swing.JLabel();
        btn_excluir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Riddle - Seleção de Funcionário");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(237, 250, 251));

        tabela_editora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tabela_editora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela_editora);

        btn_selecionar.setBackground(new java.awt.Color(227, 6, 19));
        btn_selecionar.setMaximumSize(new java.awt.Dimension(268, 50));
        btn_selecionar.setMinimumSize(new java.awt.Dimension(268, 50));
        btn_selecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_selecionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_selecionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_selecionarMouseExited(evt);
            }
        });

        label_btn2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label_btn2.setForeground(new java.awt.Color(255, 255, 255));
        label_btn2.setText("Selecionar");

        javax.swing.GroupLayout btn_selecionarLayout = new javax.swing.GroupLayout(btn_selecionar);
        btn_selecionar.setLayout(btn_selecionarLayout);
        btn_selecionarLayout.setHorizontalGroup(
            btn_selecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_selecionarLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(label_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(112, 112, 112))
        );
        btn_selecionarLayout.setVerticalGroup(
            btn_selecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(227, 6, 19));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bookriddle/imagens/white_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_busca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_busca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_busca.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txt_buscaTextValueChanged(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Áreas");

        btn_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bookriddle/imagens/black_add.png"))); // NOI18N
        btn_adicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adicionarMouseClicked(evt);
            }
        });

        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bookriddle/imagens/white_trash_small.png"))); // NOI18N
        btn_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_excluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_selecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_busca, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_excluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscaTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txt_buscaTextValueChanged
        String busca = txt_busca.getText();
        String clause = "";
        
        if (!busca.equals("")) {
            clause = "where nome like '%" + busca + "%' order by nome";
        }

        EditoraDao aDao = new EditoraDao();
        listEditora = (ArrayList<Editora>) aDao.buscarTodos(clause);
        aDao.closeConnection();
        atualizarTabela();
    }//GEN-LAST:event_txt_buscaTextValueChanged

    private void btn_selecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selecionarMouseClicked
        if (isSelected()) {
            if(cadlivro != null) {
                cadlivro.setEditora(listEditora.get(tabela_editora.getSelectedRow()));
            } else if(verLivro != null) {
                verLivro.setEditora(listEditora.get(tabela_editora.getSelectedRow()));
            } else if(editarLivro != null) {
                editarLivro.setEditora(listEditora.get(tabela_editora.getSelectedRow()));
            }
            dispose();
        }
    }//GEN-LAST:event_btn_selecionarMouseClicked

    private void btn_selecionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selecionarMouseEntered
        btn_selecionar.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_btn_selecionarMouseEntered

    private void btn_selecionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selecionarMouseExited
        btn_selecionar.setBackground(new Color(227, 6, 19));
    }//GEN-LAST:event_btn_selecionarMouseExited

    private void btn_adicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adicionarMouseClicked
        if (!txt_busca.getText().equals("")) {
            int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cadastrar a editora " + txt_busca.getText() + "?");
            if (result == 0) {
                EditoraDao aDao = new EditoraDao(new Editora(txt_busca.getText()));
                if (aDao.inserir()) {
                    JOptionPane.showMessageDialog(null, "Nova editora cadastrado com sucesso.");
                }
                listEditora = (ArrayList<Editora>)aDao.buscarTodos("where status_editora != 0 order by nome");
                aDao.closeConnection();
                atualizarTabela();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite no campo de buscas o nome da editora que deseja cadastrar.");
        }
    }//GEN-LAST:event_btn_adicionarMouseClicked

    private void btn_excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_excluirMouseClicked
        if(isSelected()) {
            Editora editora = listEditora.get(tabela_editora.getSelectedRow());
            int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir a editora " + editora.getNome());
            
            if(result == 0) {
                editora.setStatusEditora(0);
                EditoraDao aDao = new EditoraDao(editora);
                aDao.excluir();
                listEditora = (ArrayList<Editora>)aDao.buscarTodos("where status_editora != 0 order by nome");
                aDao.closeConnection();
                atualizarTabela();
            }
        }
    }//GEN-LAST:event_btn_excluirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSelecionarEditora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_adicionar;
    private javax.swing.JLabel btn_excluir;
    private javax.swing.JPanel btn_selecionar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_btn2;
    private javax.swing.JTable tabela_editora;
    private java.awt.TextField txt_busca;
    // End of variables declaration//GEN-END:variables
}
